import { MigrationInterface, QueryRunner } from 'typeorm';

export class MakeUbidAutogenerated1713095358696 implements MigrationInterface {
  name = 'MakeUbidAutogenerated1713095358696';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "occupancy_history" DROP CONSTRAINT "fk_birdhouse_occupancy_history_ubid"`,
    );
    await queryRunner.query(
      `ALTER TABLE "birdhouses" ALTER COLUMN "ubid" SET DEFAULT uuid_generate_v4()`,
    );
    await queryRunner.query(
      `ALTER TABLE "occupancy_history" ADD CONSTRAINT "fk_birdhouse_occupancy_history_ubid" FOREIGN KEY ("ubid") REFERENCES "birdhouses"("ubid") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "occupancy_history" DROP CONSTRAINT "fk_birdhouse_occupancy_history_ubid"`,
    );
    await queryRunner.query(
      `ALTER TABLE "birdhouses" ALTER COLUMN "ubid" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "occupancy_history" ADD CONSTRAINT "fk_birdhouse_occupancy_history_ubid" FOREIGN KEY ("ubid") REFERENCES "birdhouses"("ubid") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }
}
